# Makefile  —  Build configuration for the Algorithmic Online Judge.
#
# Usage:
#   make       : Compile all binaries (init_db, server, client)
#   make clean : Remove compiled binaries and temporary sandbox files

CC       = gcc
CFLAGS   = -Wall -Wextra -Iinclude
LDFLAGS  = -pthread

SRC_DIR  = src
INC_DIR  = include

.PHONY: all clean

all: init_db server client

# Standalone database initializer.
# Compiles database.c with a main() function enabled via the -D flag.
init_db: $(SRC_DIR)/database.c
	$(CC) $(CFLAGS) -DSTANDALONE_INIT -o $@ $^

# Main server daemon.
# Links all modules and requires the pthread library for multithreading.
server: $(SRC_DIR)/server.c $(SRC_DIR)/database.c $(SRC_DIR)/auth.c $(SRC_DIR)/sandbox.c
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

# CLI client terminal.
# Only requires client.c and the shared protocol structures.
client: $(SRC_DIR)/client.c
	$(CC) $(CFLAGS) -o $@ $^

# Cleanup target.
# Removes binaries and temp source files generated by the execution sandbox.
# Note: Does NOT remove the data/ directory to preserve the persistent database.
clean:
	rm -f init_db server client a.out temp.cpp temp.c
	# To reset the database completely, run: rm -rf data/ && ./init_db
